services:
  postgres:
    image: postgres:13
    networks:
      - ubc_network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    networks:
      - ubc_network

  solr:
    image: solr:8-slim
    container_name: solr_instance
    networks:
      - ubc_network
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
    command: solr-precreate alunos


  airflow-webserver:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    depends_on:
      - postgres
      - redis
    networks:
      - ubc_network
    user: "${AIRFLOW_UID:-5000}:0"
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=${AIRFLOW__CELERY__RESULT_BACKEND}
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW_ADMIN_USER=${AIRFLOW_ADMIN_USER}
      - AIRFLOW_ADMIN_PASSWORD=${AIRFLOW_ADMIN_PASSWORD}
      - AIRFLOW_ADMIN_EMAIL=${AIRFLOW_ADMIN_EMAIL}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - .:/opt/airflow/data
    ports:
      - "8080:8080"
    command: bash -c "airflow db init && airflow users create --username \"$$AIRFLOW_ADMIN_USER\" --password \"$$AIRFLOW_ADMIN_PASSWORD\" --firstname Admin --lastname User --role Admin --email \"$$AIRFLOW_ADMIN_EMAIL\" && airflow webserver"

  airflow-scheduler:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    depends_on:
      - postgres
      - redis
    networks:
      - ubc_network
    user: "${AIRFLOW_UID:-5000}:0"
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=${AIRFLOW__CELERY__RESULT_BACKEND}
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - .:/opt/airflow/data
    command: scheduler

  airflow-worker:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    depends_on:
      - postgres
      - redis
    networks:
      - ubc_network
    user: "${AIRFLOW_UID:-5000}:0"
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=${AIRFLOW__CELERY__RESULT_BACKEND}
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - .:/opt/airflow/data
    command: celery worker

networks:
  ubc_network:
    driver: bridge

volumes:
  postgres_data:
  solr_data: